# Generated by Django 5.2 on 2025-06-28 07:14

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="state",
            field=localflavor.us.models.USStateField(default="NY", max_length=2),
        ),
    ]
