# Generated by Django 5.2 on 2025-06-28 17:05

import django.db.models.deletion
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_location_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.location",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=users.utils.user_directory_path
            ),
        ),
    ]
