# Generated by Django 5.2 on 2025-08-24 14:26

import django.core.validators
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_location_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="state",
            field=localflavor.in_.models.INStateField(default="DL", max_length=2),
        ),
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid 6-digit Indian PIN code.",
                        regex="^\\d{6}$",
                    )
                ],
            ),
        ),
    ]
