# Generated by Django 5.2 on 2025-08-24 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_chathistory_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatHistory",
        ),
    ]
